#!/bin/bash
# My git script

# git init
read -p "Adding - Press enter to continue"
git add ./
read -p "Waiting for commit message:" commit
git commit -m "$commit"

#git remote add origin https://github.com/ciaranq/project2.git
read -p "Pushing - Press enter to continue"
#git push -u origin master

echo "all done "

